# numbers of generating NFT
count: 10
name: "Sunny Doll"
description: "Unique character from Rainy Land. The sunny doll variant keeps the world lively with sunshine."
image: "https://sunnydoll.com/doll/{}.png"
# rendering layer from back to front
# one component can render in multiple layers
layers:
  - folder: bg
  - folder: leg
    suffix: b
  - folder: leg
    suffix: f
  - folder: body
  - folder: ear
    suffix: b
  - folder: head
  - folder: eye
  - folder: mouth
  - folder: top
  - folder: ear
    suffix: f
# components
# weight = random distribution that calculate from weight / sum(weight of all items in the same component)
# triat_type and trait_value are for metadata generation
components:
  - trait_type: Background
    folder: bg
    items:
      - trait_value: "White Wall"
        weight: 50
      - trait_value: "Spotlight"
        weight: 40
      - trait_value: "Grass"
        weight: 10
  - trait_type: Body
    folder: body
    items:
      - trait_value: "Black Shirt"
        weight: 1
      - trait_value: "Heart T-Shirt"
        weight: 1
      - trait_value: "Sunny Shirt"
        weight: 1
  - trait_type: Ears
    folder: ear
    items:
      - trait_value: "Long Ears"
        weight: 1
      - trait_value: "Mouse"
        weight: 1
      - trait_value: "Dog"
        weight: 1
  - trait_type: Eyes
    folder: eye
    items:
      - trait_value: "Cyclop"
        weight: 1
      - trait_value: "Angry"
        weight: 1
      - trait_value: "Cute"
        weight: 1
  - trait_type: Head
    folder: head
    items:
      - trait_value: "Round"
        weight: 1
      - trait_value: "Furry"
        weight: 1
      - trait_value: "Cute"
        weight: 1
  - trait_type: Legs
    folder: leg
    items:
      - trait_value: "Slender"
        weight: 1
      - trait_value: "Tights"
        weight: 1
      - trait_value: "Boots"
        weight: 1
  - trait_type: Mouth
    folder: mouth
    items:
      - trait_value: "Cute"
        weight: 1
      - trait_value: "M"
        weight: 1
      - trait_value: "Triangle"
        weight: 1
  - trait_type: Top
    folder: top
    items:
      - # no top
        weight: 4
      - trait_value: "Mohawk"
        weight: 3
      - trait_value: "Hat"
        weight: 3
